### ISSUE TITLE
Cannot Setup USB Serial

### ISSUE THREAD

**Issue by yishiyang** [inventit/processing-android-serial#6]
Hi,  I'm trying to use the library. It's a very simple sketch:

import com.yourinventit.processing.android.serial.*;

Serial myPort;  // The serial port

void setup() {
  //canvas
  size(2560, 1600);
}

void draw() {
  
  for(int i=0;i<Serial.list(this).length;i++)
  {
    text(Serial.list(this)[i], 100, 100*i);
  }
 
    // Open the port you are using at the rate you want:
  myPort = new Serial(this, Serial.list(this)[0], 4800);
  
  while (myPort.available() > 0) {
    int inByte = myPort.read();
    text(inByte, 400,200);
  }
}

But got an error like this: 

FATAL EXCEPTION: Animation Thread
Process: processing.test.usb_serial, PID: 7501
java.lang.IllegalStateException: Cannot setup USB Serial.
	at com.yourinventit.processing.android.serial.UsbSerialCommunicator.doStart(UsbSerialCommunicator.java:108)
	at com.yourinventit.processing.android.serial.AbstractAndroidSerialCommunicator.start(AbstractAndroidSerialCommunicator.java:333)
	at com.yourinventit.processing.android.serial.AbstractAndroidSerialCommunicator.start(AbstractAndroidSerialCommunicator.java:308)
	at com.yourinventit.processing.android.serial.AbstractAndroidSerialCommunicator.start(AbstractAndroidSerialCommunicator.java:297)
	at com.yourinventit.processing.android.serial.Serial.<init>(Serial.java:51)
	at com.yourinventit.processing.android.serial.Serial.list(Serial.java:263)
	at processing.test.usb_serial.USB_Serial.draw(USB_Serial.java:34)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:841)

Please help! Thanks a lot!

**Comment by dbaba** [comment]
It seems that your Android didn't recognize your hardware. Are you sure to place a device_filter.xml?
Please refer to the [sample AndroidManifest.xml and device_fiter.xml](https://github.com/inventit/processing-android-serial/tree/master/src/main/examples/PulseSensor11574).

Or your USB venrodrId and productId are unfortunately unsupported.
Please have a look at the [code](https://github.com/inventit/usb-serial-for-android/blob/master/UsbSerialLibrary%2Fsrc%2Fcom%2Fhoho%2Fandroid%2Fusbserial%2Fdriver%2FUsbId.java), where you can find acceptable vendorIds and productIds.

**Comment by DaveB1800** [comment]
On a similar note, I have been trying to read serial data from an Xbee S2B via a USB Xbee Explorer to an android device.  Using the 'USB DEVICE INFO' app it is detecting the explorer as Vendor ID 0403 and Product ID 03ea.  Data can be read into the device using serial monitor app, so connection, drivers, data sending are all working fine.

After modifying the AndroidManifest.xml and device_filter.xml yesterday my Processing sketch worked fine and read the data from the serial port.  I had modified the first entry within resources on the device_filter.xml as this appeared to have the same Vendor ID, so that it read
<!- 0x0403 / 0x6001:FTDI FT232R UART ->
<usb-device vendor-id='0403' product-id='03ea'/>

  Today without any further modifications, I'm getting a
 java.lang.IllegalStateException: Cannot setup USB Serial.
Looking at your link above - Product ID 03ea does not seem to be supported - so I'm not quite sure how I got it working yesterday?  Was this a complete fluke or can you see a way of restoring communication?
I've tried various combinations of decimal / hex id's and of course modifying 0x6001 (the FT232R id) in the first line with my 03ea id.
Is it possible to 
1. Modify / add a resource to the file to recognize the explorer
2. Get the ProcessingAndriodSerial to support the device
or 3. Purchase an Xbee explorer which is supported?
the fact that it worked yesterday compels me to keep trying!

**Comment by DaveB1800** [comment]
Further to the above  - I've just discovered that plugging the Xbee explorer into a windows laptop, the device manager returns Vid/Pid 0403/  6001 which is what you might expect, and which I guess would run properly.  I have no clue why it appears on my android 4.4.4 device as 0403 / 03ea.  I'm guessing now that this is not an issue with processingAndroidSerial but with my device.  However if you can shed any light on this and point me in the direction of searching out a solution that would be great, as I am now at a loss!

**Comment by yishiyang** [comment]
@DaveB1800  thanks for sharing the information. 
@dbaba you are probably right. 
I got mine working bypassed the usb serial because I found the hardware I'm using actually requires a driver to be recognized by Android, so I wired the hardware to an arduino and plug the arduino to android as a HID device, and it worked. But I didn't use this library so still not sure.
